app.json
ui/ContentView.tsx

https://github.com/gkasdorf/memmy/issues/14

Fix images not loading in feed view

---

app/onboarding/addAccount.tsx
app/onboarding/createAccount.tsx
app/tabs/settings/editAccount.tsx
lemmy/LemmyInstance.ts
lemmy/types/ILemmyServer.ts
ui/CTextInput.tsx

If the server returns the error `missing_totp_token`, this commit adds a 2FA Token TextInput to the Add and Edit Account forms.

Add TOTP to Add and Edit Account screens

---

components/ui/CommunityLink.tsx
components/ui/ContentView.tsx
components/ui/Feed/FeedItem.tsx
helpers/TextHelper.ts

- Change the `FeedItem` layout to have the Community link at the top
- Increase how much is truncated off the post preview

Change FeedItem layout

---

components/screens/settings/SettingsIndexScreen.tsx
components/ui/CommentItem.tsx
slices/settings/settingsSlice.ts

- Setting to display or hide instance name from user name
- Fix padding issues

Comment tweaks

---

components/hooks/post/postHooks.ts
components/ui/CommentItem.tsx
components/ui/Feed/FeedItem.tsx
helpers/HapticFeedbackHelpers.ts

This is to make creating custom patterns easier as well as making the code easier to understand: 
`trigger("vibrationName") -> onActionHapticFeedback()` 
The choice of the pattern in the helper file may not work the same on iOS and on Android. For instance, the impactMedium vibration type on my phone was just a soft vibration, not an "impact" like a knock. So this file could also be useful for creating platform specific patterns.
I do not have an iPhone to test out the pattern I did, but on my phone (S23) it does one heavy knock and a smaller one.

Create Haptic feedback helper file

---

.gitignore

This is just the default expo gitignore, along with the old one. I also added android/ to the list

Add the default Expo .gitignore

---

components/screens/post/PostActionBar.tsx
components/screens/post/PostBody.tsx
components/screens/post/PostScreen.tsx
components/ui/CommentItem2.tsx
components/ui/CommunityLink.tsx
components/ui/ContentView.tsx
components/ui/Feed/FeedItem.tsx
components/ui/LinkButton.tsx
components/ui/UserLink.tsx
components/ui/common/AvatarUsername.tsx
components/ui/common/IconButtonWithText.tsx
components/ui/common/VoteButton.tsx
helpers/LinkHelper.ts
lemmy/LemmyHelpers.ts
theme/theme.ts

Improve appearance of viewing content on FeedItem and in a PostScreen

Improvements around PostScreen and FeedItem

---

components/ui/Feed/FeedItem.tsx
components/ui/LinkButton.tsx

Tweak the url thumnail preview and upvote icons.

Tweak some FeedItem displays

---

components/ui/buttons/ButtonOne.tsx
components/ui/buttons/ButtonTwo.tsx
theme/theme.ts

try to replicate somewhat the other figma themes. button one and button two both use the styles now. probably can reduce these down to one button.

other themes

---

components/hooks/feeds/useFeed.ts
components/hooks/feeds/useFeedItem.ts
components/ui/Feed/CompactFeedItem/CompactFeedItem.tsx
components/ui/Feed/FeedItem.tsx
components/ui/Feed/FeedView.tsx
theme/theme.ts

Adjusted the style of the post title/name to use a different text color when a post has been read/viewed already.
Currently, the feed needs to be refreshed to reflect the change. Not sure if there is a way to force a single post to be refreshed/redrawn when going back to the main feed.

Adjusted post name style to show when a post has been read/viewed

---

components/screens/settings/SettingsIndexScreen.tsx

This minor PR should fix #187. Sorry!

Bug fix in haptic sensitivity implementation

---

Stack.tsx
components/screens/post/NewCommentScreen.tsx
components/screens/post/NewPostScreen.tsx
components/screens/settings/EditAccountScreen.tsx
components/screens/userProfile/BookmarksScreen.tsx
components/ui/Feed/CompactFeedItem/CompactFeedItemThumbnail.tsx
components/ui/buttons/ImageButton.tsx
components/ui/buttons/LinkButton.tsx
components/ui/markdown/RenderMarkdown.tsx
theme/common.ts
theme/darkColors.ts
theme/lightColors.ts
theme/theme.ts
theme/themeOptions.ts

Add new themes from @teflocarbon and remove some extra theme props i didn't like

Add New Themes and Tweak Theme Obj

---

Stack.tsx
components/ui/ContentView.tsx
components/ui/Feed/FeedItem.tsx
components/ui/buttons/LinkButton.tsx
components/ui/image/ImageModal.tsx

Refactor ContentView to be easier to work with, fix some title stuff.

Refactor ContentView

---

components/ui/search/SearchBar.tsx

When navigation to the Search screen this will focus the search input to make it easier/faster to start searching.

focus searchbar input on tab press

---

components/ui/ContentView.tsx

Display body content if an image post has a body
Adjust margin on all types of content

Fix content view to show image body

---

components/screens/post/NewPostBodyScreen.tsx

fix: NewPostBodyScreen lint error

---

app.json
components/ui/Feed/FeedOverflowButton.tsx
components/ui/Feed/FeedSortButton.tsx
components/ui/Feed/FeedView.tsx
components/ui/Feed/Footer.tsx

Came across your post on Reddit on this day of mourning. Thought i'd check out the project and was delighted to see it was RN. Thought i'd contribute a bit, if you're willing.
This PR does a few things:
1. It stabilizes the callbacks to FlashList (you usually want to stabilize virtualized list props as much as possible, as not doing it can chew performance)
2. Removes the inline functional component definitions (`footer`). This is a big one, as we were creating a new functional component on every render pass. Doing so prohibits React from optimizing the component, as we're blowing it away every time.
3. Cleans up the files a bit by creating some domain-specific components (`OverflowMenuButton`, `FeedSortButton`) for the Feed
Usually i would use Flipper and flamegraph the screen, but alas, …

`FeedView` optimizations

---

components/screens/post/NewPostBodyScreen.tsx
components/ui/KeyboardAccessory.tsx

- Update the icons to use tabler
- Move the component outside of KeyboardAwareScrollView
- Add prompts for accepting the links.

improvements to keyboard accessory

---

components/hooks/inbox/useInbox.ts
components/screens/inbox/InboxScreen.tsx
components/ui/inbox/InboxReplyItem.tsx

Remove unnecessary useMemos
Create separate InboxItem component for the list
Cleaned up anonymous funcs

cleanup inbox

---

components/hooks/profile/useProfile.ts
components/screens/userProfile/UserProfileScreen.tsx
components/ui/Feed/CompactFeedItem/CompactFeedItem.tsx
components/ui/markdown/RenderMarkdown.tsx
components/ui/profile/ProfileCommentList.tsx
components/ui/profile/ProfilePostList.tsx
components/ui/profile/ProfileRefreshControl.tsx
components/ui/profile/ProfileSavedPostList.tsx

- Break down the profile screen
- Remove needless memos
- Re-render screen on account change
- Properly memoize compact feed item

Refactor profile view

---

components/hooks/post/postHooks.ts
components/screens/post/PostScreen.tsx
lemmy/comments/LemmyCommentsHelper.ts

- Fixed comments not loading correctly when a child comment comes before the parent comment in the api response.
- Fixed the sorting of comments after hitting "Load all comments...".

Fixed nested comment issues

---

components/screens/onboarding/AddAccountScreen.tsx
components/screens/onboarding/CreateAccountScreen.tsx
components/screens/settings/EditAccountScreen.tsx
components/screens/traverse/TraverseScreen.tsx

Allow taps to be handled when the keyboard is displayed

Fix keyboards inside of scrollviews

---

helpers/LinkHelper.ts
package.json

- Added support for non-lemmy urls that are formatted like lemmy urls
- Fixed support for links to lemmy communities on other lemmy instances
- Preparing for an "Open in Memmy" Safari extension

Fixed link handling bugs

---

Stack.tsx
assets/terms.html
components/hooks/post/useComment.ts
components/screens/ViewerScreen.tsx
components/screens/onboarding/AddAccountScreen.tsx
components/screens/onboarding/CreateAccountScreen.tsx
components/screens/post/PostScreen.tsx
components/screens/settings/SettingsIndexScreen.tsx
components/screens/userProfile/UserProfileScreen.tsx
components/ui/post/PostOptionsButton.tsx

- Block users
- Report posts
- Report comments
- Add terms

changes for apple

---

Stack.tsx
components/screens/feeds/CommunityAboutScreen.tsx
components/screens/feeds/CommunityFeedScreen.tsx
components/screens/settings/About/AboutScreen.tsx
components/screens/settings/Account/AccountSettingsScreen.tsx
components/screens/settings/Account/EditAccountScreen.tsx
components/screens/settings/Account/PushNotificationsScreen.tsx
components/screens/settings/Account/ViewAccountsScreen.tsx
components/screens/settings/Appearance/AppearanceScreen.tsx
components/screens/settings/Appearance/ThemeSelectionScreen.tsx
components/screens/settings/Content/ContentScreen.tsx
components/screens/settings/Content/ReadSettingsScreen.tsx
components/screens/settings/General/GeneralSettingsScreen.tsx
components/screens/settings/SettingsIndexScreen.tsx
components/ui/Feed/FeedView.tsx
components/ui/table/CSection.tsx
components/ui/traverse/TraverseItem.tsx
theme/darkColors.ts

- Fix bug where community header doesn't display for communities (#367)
- Add icon to traverse communities that don't have an icon (#363)
- Update settings page

Settings Page Update/Random bugfixes

---

components/ui/Feed/FeedHeaderDropdownDrawer.tsx
slices/accounts/accountsActions.ts
slices/accounts/accountsSlice.ts
types/Account.ts

When I set my current account, mark it as such in the account store so that the next time I re-open the app, the same account/feed is opened.

Remember last used account when app is re-opened

---

components/hooks/post/useComment.ts

I added an option in the comment dropdown to Reply to a comment. There's been several posts about not knowing how to reply.

Added a Reply dropdown to the comment menu

---

package.json
src/components/common/SwipeableRow/ReplyOption.tsx
src/components/common/SwipeableRow/VoteOption.tsx
src/components/screens/Feed/components/FeedHeaderDropdownDrawer.tsx

Fixes #458
This PR:
- adds a `lint` command to package.json (`yarn lint` - yay!)
- increases the size and duration of a Vote/Reply option pulses when they cross activation
- speeds up the arrow roation
- fixes funky arrow rotation bug
Next up on my plate is to move these animations into shared worklets and get rid of the copy pasta.

Fix arrow rotation bug & other minor improvements

---

src/components/screens/Feed/components/FeedView.tsx

When checking Compact View the feed will be updated through the `<FlashList/>` prop `extraData`.
fixes #421

fix compact view update with FlashList.extraData #421

---

src/components/screens/UserProfile/UserProfileScreen.tsx

Added a missing dependency to the useEffect in UserProfileScreen.

Fix blocking users

---

src/components/common/Comments/CommentItem.tsx

Improper logic in the equality check resulted in a post not editing or deleting.

Fix comment not editing or deleting correctly

---

src/slices/accounts/accountsActions.ts

Update account token

---

src/components/common/Buttons/LinkButton.tsx
src/components/common/Buttons/WebLink.tsx
src/components/common/Markdown/RenderMarkdown.tsx
src/components/screens/Settings/About/AboutScreen.tsx
src/helpers/LinkHelper.ts

The browser toolbar will use the background color of the currently selected theme now.

Browser conforms to current theme

---

src/components/screens/Post/NewPostScreen.tsx

Hi! I wanted to contribute, and this looked like low hanging fruit ✨ 
Uses `accent` color for header buttons in the new post screen, as well as the camera icon for links. Made an assumption for the camera button, since that seemed more aligned with the design other places. Let me know if that's not correct ✌️
fixes https://github.com/Memmy-App/memmy/issues/659
<div>

use accent colors on NewPostScreen

---

App.js
src/components/common/ImageViewer/ImageExitButton.tsx
src/components/common/ImageViewer/ImageViewer.tsx

Image viewer changes

---

src/plugins/i18n/locales/cz.json

> Czech translations as per discussion on Lemmy
> Switch to Czech and check if there is no issue with translation string length

Czech translations

---

src/helpers/LinkHelper.ts
src/plugins/i18n/locales/cz.json
src/plugins/i18n/locales/de.json
src/plugins/i18n/locales/en.json

- Fixes issues with invalid links. Return on URL validation failure
- Fix issues where lemmy instances that have a subdomain won't be validated as such

add a check to prevent crashes

---

README.md

It provides a `Requirements` section to the Readme.md
1. Open the Readme file
1. Check all the links if they link to the correct website
----------------
resolves #687

Add Requirements info to README.md

---

src/components/common/Search/SearchCommunityItem.tsx
src/components/common/Table/MCell.tsx
src/helpers/NumberHelper.ts

Add Subscriber count to Community Search

---

ios/Podfile.lock
package.json
src/components/common/AvatarUsername.tsx
src/components/common/Buttons/LinkButton.tsx
src/components/common/CommunityLink.tsx
src/components/common/ImageViewer/ImageViewFooter.tsx
src/components/common/ImageViewer/ImageViewer.tsx
src/components/common/MemoizedFastImage.tsx
src/components/common/Search/GenericSearchResult.tsx
src/components/common/Search/SearchCommunityItem.tsx
src/components/common/Search/SearchUserItem.tsx
src/components/screens/Feed/CommunityAboutScreen.tsx
src/components/screens/Feed/CommunityFeedScreen.tsx
src/components/screens/Feed/components/CompactFeedItem/CompactFeedItemThumbnail.tsx
src/components/screens/Feed/components/FeedItem/FeedItem.tsx
src/components/screens/HubDiscovery/InstanceScreen.tsx
src/components/screens/HubDiscovery/components/InstanceItem.tsx
src/components/screens/Settings/SettingsIndexScreen.tsx
src/components/screens/Traverse/components/TraverseItem.tsx
src/components/screens/UserProfile/components/ProfileHeader.tsx
src/helpers/ImageHelper.ts
src/helpers/ShareHelper.ts
yarn.lock

- Replace FastImage with patched version to allow us to retrieve the cached image file path

replace fast-image with patched version

---

src/components/common/Comments/CommentActions.tsx
src/components/common/Comments/CommentHeader.tsx
src/components/common/Comments/CommentItem.tsx
src/components/common/ImageViewer/ImageExitButton.tsx
src/components/common/ImageViewer/ImageViewFooter.tsx
src/components/common/ImageViewer/ImageViewer.tsx
src/components/common/Vote/SmallVoteIcons.tsx
src/components/screens/Feed/components/CompactFeedItem/CompactFeedItemThumbnail.tsx
src/components/screens/Feed/components/FeedItem/Actions.tsx
src/components/screens/Feed/components/FeedItem/Metrics.tsx
src/components/screens/Post/PostScreen.tsx
src/components/screens/Post/components/PostHeader.tsx
src/components/screens/UserProfile/UserCommentsScreen.tsx
src/hooks/feeds/useFeedItem.ts
src/hooks/post/postHooks.ts
src/hooks/post/useComment.ts

- Image viewer improvements and fixes

fix: nsfw images now open iimage viewer in compact mode

---

src/components/common/Navigation/CustomTabBar.tsx
src/components/common/Navigation/TabBarGestureHandler.tsx

Adds a swipe-to-pop gesture to the tab bar.

feat: add gestures to tab bar

---

src/components/screens/Feed/CommunityFeedScreen.tsx
src/helpers/NumberHelper.ts

fix subscriber count

---

Stack.tsx
src/components/screens/Inbox/InboxScreen.tsx
src/hooks/inbox/useInbox.ts

- Memoize functions
- Refresh the inbox on screen focus

Inbox Cleanup

---

src/components/common/ImageViewer/ImageViewer.tsx

remove unnecessary divide for pan update

---

src/components/screens/Traverse/TraverseScreen.tsx

Makes searches case insensitive on the traverse screen
1. Use a capitalized search term to find a community with only lowercase

Traverse Screen case insensitive searching

---

src/components/common/Comments/CommentActions.tsx
src/components/common/Comments/CommentItem.tsx

798-bug-comment-reply-button-doesnt-work

---

src/components/screens/Post/PostScreen.tsx
src/hooks/post/usePost.ts
src/stores/posts/actions/addPost.ts
src/stores/posts/actions/refreshPost.ts
src/stores/posts/postsStore.ts

Post refreshes as well when refreshing comments.

fix: refresh post data on refresh

---

ios/Memmy/Info.plist

Attempt at getting third-party mail clients to work.

fix: allow for opening debug email in other clients besides mail.app

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

fix typo in PR template
fix a typo
-

Update pull_request_template.md - fix typo

---

Start.tsx
src/components/common/Vote/VoteButton.tsx
src/components/screens/Feed/components/FeedItem/FeedItem.tsx
src/components/screens/Feed/components/FeedView.tsx
src/components/screens/Settings/Content/ReadSettingsScreen.tsx
src/plugins/i18n/locales/en.json
src/slices/settings/settingsSlice.ts

feat: Mark post read on scroll

---

Stack.tsx
Start.tsx
src/components/screens/Settings/Filters/FiltersScreen.tsx
src/components/screens/Settings/Filters/InstancesScreen.tsx
src/components/screens/Settings/Filters/KeywordsScreen.tsx
src/components/screens/Settings/SettingsIndexScreen.tsx
src/constants/IconMap.ts
src/plugins/i18n/locales/en.json
src/stores/feeds/actions/loadFeedPosts.ts
src/stores/filters/filtersStore.ts

Adds keyword and instance filtering.

feat: Add keyword and instance filtering

---

src/components/common/Buttons/LinkButton.tsx
src/components/common/IconButtonWithText.tsx
src/components/common/ImageViewer/ImageViewer.tsx
src/components/common/SwipeableRow/VoteOption.tsx
src/components/screens/Feed/components/CompactFeedItem/CompactFeedItem.tsx
src/components/screens/Feed/components/CompactFeedItem/CompactFeedItemFooter.tsx
src/components/screens/Feed/components/CompactFeedItem/CompactFeedItemThumbnail.tsx
src/components/screens/Feed/components/FeedContentPreview.tsx
src/components/screens/Feed/components/FeedItem/FeedItem.tsx
src/components/screens/Feed/components/FeedItem/Metrics.tsx
src/components/screens/Feed/components/FeedView.tsx
src/hooks/feeds/useFeedItem.ts
src/stores/feeds/feedsStore.ts

create selectors and use stable values for re-renders

---

src/components/screens/Feed/components/FeedView.tsx

fix: infinite refresh attempts on empty community

---

ios/.xcode.env

Fixes obscure build issue where the blank line causes one of the scripts to fail with `command not found: `.
> Please document the steps required to test your PR
Build on other developer's environments to ensure all good.

Fix build issue

---

src/components/common/Comments/CommentItem.tsx
src/components/common/Comments/ShowMoreButton.tsx
src/components/screens/Post/PostScreen.tsx
src/components/screens/Post/components/PostCommentItem.tsx
src/components/screens/UserProfile/UserCommentsScreen.tsx
src/components/screens/UserProfile/components/ProfileCommentItem.tsx
src/hooks/profile/useProfile.ts
src/stores/posts/actions/addPost.ts
src/stores/posts/postsStore.ts

fix: take user directly to comment when tapping a comment in profile

---

Stack.tsx
src/LemmyInstance.ts
src/components/screens/Settings/Appearance/AppearanceScreen.tsx
src/stores/settings/settingsStore.ts
src/stores/site/siteStore.ts

Implements #837 
Tested with multiple accounts (switching) and with accounts that have no avatar image.

Add avatar image in tab bar; add setting to disable showing image.

---

src/components/screens/Settings/SettingsIndexScreen.tsx
src/plugins/i18n/locales/en.json

feat: add instance status button to settings

---

README.md

This fixes minor linting errors such as spacing, and incorrect levels.
(check diff)

[Docs] Fix lint errors in README.md

---

src/components/screens/Post/components/PostCommentItem.tsx

fix: tap to collapse disable

---

src/helpers/LinkHelper.ts

fix: dont use hook to get current account

---

src/components/screens/Feed/components/CompactFeedItem/CompactFeedItemThumbnail.tsx

cleanup set post read logic for compact

---

src/components/screens/Post/PostScreen.tsx

Fix comment jump not updating on scroll

---

src/components/common/ImageViewer/ImageViewer.tsx
src/components/common/KeyboardAccessory.tsx
src/components/common/Search/SearchBox.tsx
src/components/common/Table/MTable.tsx
src/components/screens/Feed/components/Community/ModeratorList.tsx
src/components/screens/Feed/components/CompactFeedItem/CompactFeedItem.tsx
src/components/screens/Feed/components/CompactFeedItem/CompactFeedItemVote.tsx
src/components/screens/Feed/components/FeedItem/Actions.tsx
src/components/screens/Post/PostScreen.tsx
src/components/screens/Post/components/PostActionBar.tsx
src/components/screens/Post/components/PostFooter.tsx
src/components/screens/Search/SearchResultsScreen.tsx
src/components/screens/Traverse/TraverseScreen.tsx
src/components/screens/UserProfile/UserPostsScreen.tsx
src/helpers/TextHelper.ts

fix some checks, missing keys, and renders

---

ios/Podfile.lock
package.json
src/components/common/ContextMenu/ImageContextMenu.tsx
src/components/common/ImageViewer/ImageViewer.tsx
yarn.lock

Add context menu to image viewer

---

src/components/common/AvatarUsername.tsx
src/components/common/Buttons/ImageButton.tsx
src/components/common/Buttons/LinkButton.tsx
src/components/common/ImageViewer/ImageViewer.tsx
src/components/common/Markdown/RenderMarkdown.tsx
src/components/screens/Feed/components/Community/CommunityCounts.tsx
src/components/screens/Feed/components/FeedContentPreview.tsx

Many fixes
