Memmy-App/memmy

- components/ui/CommentItem.tsx
When reusing a comment component update the vote state (upvoted, neutral, down-voted) from the API data.
Prevents having an 'old' state used for a component when it's reused.
> Fixes gkasdorf/memmy#39

- components/screens/post/PostScreen.tsx
- components/ui/comments/CommentItem2.tsx
- components/ui/common/AvatarUsername.tsx
- components/ui/markdown/RenderMarkdown.tsx
We were using `creator.actor_id` instead of `community.actor_id` to display the instance name for a community.
> Fix Instance URL in Post Screen

- components/screens/settings/SettingsIndexScreen.tsx
- components/ui/Feed/CompactFeedItem/CompactFeedItem.tsx
- slices/settings/settingsSlice.ts
Option for hiding voting buttons in compact view, also creates a section under settings for compact specific settings
> feat: hide compact voting buttons setting

- components/screens/feeds/CommunityFeedScreen.tsx
- components/ui/buttons/CustomButton.tsx
* Community icon fallback to icon planet
* Made it possible to fill icons, making subscribe icon look better in different themes
| Before  | After |
| ------------- | ------------- |
| <img src="https://github.com/gkasdorf/memmy/assets/2129171/daba6e4a-58f6-4ae9-94cd-c27d9faa80b8" width="300" />   | <img src="https://github.com/gkasdorf/memmy/assets/2129171/b9979f5b-913d-489b-9870-ca1eee43002c" width="300" /> |
> fix: community icon fallback to planet icon and subscribed icon fill

- components/ui/Feed/FeedView.tsx
- components/ui/customIcons/IconCalendarWeek.tsx
- components/ui/customIcons/index.ts
Since both top day and top week icons where the same and no icon counterpart for week existed I created one. 
Works the same as the other icons.
> add calendar week icon for sort

- components/screens/settings/SettingsIndexScreen.tsx
Thumbnail position setting showActionSheetWithOptions gets light mode when dark mode is active.
> fix: thumnail position setting dark mode

- components/ui/Feed/FeedOverflowButton.tsx
- components/ui/Feed/FeedSortButton.tsx
- components/ui/buttons/HeaderIconButton.tsx
Sorry if I didn't create an issue first, not sure if you would prefer me to do that. I can create one if so, or I can close this if it's not on the roadmap, or if I was stepping on another devs toes.
I noticed that actively pressing the header buttons doesn't highlight them. When a user presses and holds the button, it may be unclear which one they are pressing. Adding the highlight color can help aid that.
This PR also adds `(current)` next to the currently selected feed filter action sheet, which was a requested feature in discord.
**Hot is actively being pressed in this screenshot**
**Currently selected filter**
**Currently selected filter inside a community**
> feat: improve header button and feed filter

- components/screens/settings/SettingsIndexScreen.tsx
- components/ui/Feed/FeedSortButton.tsx
- types/FeedSortOptions.ts
This PR fixes #289. As discussed there, this also refactors `sortOptions` to `types/` from `FeedSortButton`.
> Fix default sort option display

- Start.tsx
- components/screens/settings/SettingsIndexScreen.tsx
- slices/settings/settingsSlice.ts
- theme/common.ts
Allow system font to be used instead of the included Inter font.
BTW.. I was going to add a menu with some additional font options (probably Roboto, Roboto Condensed, Oswald), but I am not sure where you got or how you generated the OTF format fonts with the 200/600/800 weights that aren't provided by google.
> New setting to allow system font to be used instead of bundled font

- components/ui/Feed/CompactFeedItem/CompactFeedItemThumbnail.tsx
Subjective thing, but... I found that when there were many Link type posts, the rows in compact mode looked very indistinct.
I went back to a video I took of Apollo and found that they used an indicator at the bottom right of the thumbnail:
I did something similar here:
I don't actually understand what the units are for top/bottom on the absolute positioning of the View but everything seems to line up so hopefully that will continue to work for all device configurations.
> Move link indicator to corner of compact thumbnail

- components/screens/settings/SettingsIndexScreen.tsx
- slices/settings/settingsSlice.ts
This addresses one of the requests in #182. Not much to change since thumbnail container was already checking for Left or Right position setting before rendering.
> Hide thumbnails

- app.json
- ios/Memmy.xcodeproj/project.pbxproj
- ios/Podfile
- ios/Podfile.lock
- ios/Podfile.properties.json
- package.json
- yarn.lock
This allows for flipper support. I've left the flag inside of the podfile set to disabled (I need to look into what the best practice is for enabling/disabling this)
If you want to use flipper, just enable the flag and rebuild after a pod install.
> flipper suport

- helpers/LinkHelper.ts
There was an issue where accounts.currentAccount would be null on first launch. This fixes that by re-grabbing the state if it was null.
> Re-grab "accounts" from the state store if currentAccount is null

- package.json
This package is not needed as its functionality has been merged into the react core. I inadvertently added it in #354. The version referenced in the package.json is old and no longer updated.
It didn't really cause any problems with the iOS build at this point, but when I made an Android build out of curiosity, it caused the build to fail since the library hasn't been updated to be built with recent gradle versions.
Wasn't sure if you wanted the yarn.lock and Podfile.lock included (I can add them to PRs if preferred) or you want to regenerate them yourself... Not sure I'm running the exact same version of these package managers as you.
> Remove unused react-native-appearance package

- components/ui/post/PostOptionsButton.tsx
Added a duration to the toast confirming a post was reported. It was previously persistent until app restart.
> Updated toast for reporting a post

- src/components/screens/Feed/components/FeedView.tsx
Fixes https://github.com/Memmy-App/memmy/issues/508
Default view (non-compact). Note the button acts like the other buttons where it shows the current view (in this case, the medium icon) and clicking it switches to the other view.
After clicking the icon, the app switches to compact view.
Clicking again shows the default view (non-compact).
> Add header button to toggle compact view

- src/components/screens/Post/components/PostOptionsButton.tsx
fixes #577 and maybe #511 
You can now also use the 'clickAway' method to close the menu just like the comments menu
https://github.com/Memmy-App/memmy/assets/50131232/316aed34-7160-4820-b837-6506fa993eef
1. Open the app
2. Open a post of your choice
3. click the 3 vertical dots at the top right (posts menu)
4. click anywhere where there is no buttons
5. menu should close
```
> fix post menu view & cancel behaviour. fixes #577 and #511

- src/components/common/ImageViewer/ImageViewFooter.tsx
- src/helpers/ImageHelper.ts
- src/helpers/ShareHelper.ts
If the network times our or something else happens to an image download, currently the image download dialog does not disappear after that timeout. This fixes those issues. Also, images are deleted from the filesystem after being shared or after being added to the camera roll.
> delete image after share

- src/components/common/KeyboardAccessory.tsx
Super basic, was not using the correct localization key for the link wizard prompts.
> fix link wizard translation

- src/helpers/ImageHelper.ts
Now displays an error message if there are no permissions to save the image (after the initial request. Initial request still asks for permission)
> display dialog if permissions are not granted

- src/components/screens/Post/components/PostHeader.tsx
- src/components/screens/Settings/Appearance/AppearanceScreen.tsx
- src/hooks/post/useComment.ts
- src/plugins/i18n/locales/cz.json
- src/plugins/i18n/locales/de.json
- src/plugins/i18n/locales/en.json
- src/slices/settings/settingsSlice.ts
Option to enable or disable tap to collapse (default is true)
> add setting for tap to collapse

- src/components/common/KeyboardAccessory.tsx
- src/helpers/ImageHelper.ts
- src/types/ErrorCause.ts
when opening the image picker in a new post or a new comment and then clicking cancel the error alert no long appears
When opening the image picker in a new post or a new comment and then clicking cancel the error alert no long appears
https://github.com/Memmy-App/memmy/assets/50131232/a05393e3-80f1-4925-acb7-fcdbbd9ebfb4
https://github.com/Memmy-App/memmy/assets/50131232/4329c446-c136-4b79-8f1c-9e0aac1c2ac7
1. Open lemmy app
2. Navigate to any community where you have a `+ Post` Button available
3. Press the `+ Post` Button
4. Click the image icon at the bottom right to open the img picker
5. Press `Cancel` at the top left
6. There should be NO alert anymore
1. Open lemmy app
2. Open any Post where you can comment on
3. Press …
> Cancelling image picking causes Alert "Imgur upload failed" [fixes #628]

- src/helpers/LemmyHelpers.ts
Should have been doing this from the start, but it is rather confusing how Lemmy handles this. Anyway, we now filter out NSFW posts based off of both the community flag and the post flag.
> Fix: Filtering of NSFW from the feed now checks for community NSFW flag

- src/plugins/i18n/locales/en.json
it was "Most Comments" but is now "New" (as it should)
fixes #872 
Unfortunately I cannot provide proof screenshots as the build is broken right now
> fix sort.New translation error

- src/components/screens/Settings/Content/ContentScreen.tsx
- src/components/screens/Settings/General/GeneralSettingsScreen.tsx
- src/plugins/i18n/locales/cz.json
- src/plugins/i18n/locales/de.json
- src/plugins/i18n/locales/en.json
- src/plugins/i18n/locales/pt_br.json
- src/plugins/i18n/locales/ro.json
Moves the option to open internal web links in reader mode to the General section where the option to use Default Browser is. Also hides the option when internal browser is not being used.
> Move browser settings into General section

- src/hooks/contextMenu/useFeedSortOptions.ts
- src/hooks/contextMenu/useTopSortOptions.ts
fixes a wrong `top week` label in the feed sort options
Unfortunately I can't test it cause of this error:
Take a look at the resolved comments it was quite the easy fix
> Fix sort.top.Week using wrong label (sort.top.Hour)
